language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/Document/MGL/Unit\ testing/gradle/

script:
  - ./gradlew test
  
before_script:
 - chmod +x ./gradlew build connectedCheck
